openapi: 3.0.3

info:
  contact: {}
  description: This API is used to manage applications.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Application Management API
  version: "1.0"

servers:
  - url: https://{host}:{port}
    variables:
      host:
        default: "localhost"
      port:
        default: "8090"

paths:
  /applications:
    get:
      description: Retrieve a list of all applications.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/model.Application'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: List applications
      tags:
      - applications
    post:
      description: Creates a new application with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Application'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.Application'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: Create an application
      tags:
      - applications
  /applications/{id}:
    delete:
      description: Delete an application using its ID.
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 'Not Found: The application with the specified ID does not exist.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: Delete an application
      tags:
      - applications
    get:
      description: Retrieve a specific application using its ID.
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.Application'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 'Not Found: The application with the specified ID does not exist.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: Get an application by ID
      tags:
      - applications
    put:
      description: Update the details of an existing application.
      parameters:
      - description: Application ID
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.Application'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.Application'
        "400":
          description: 'Bad Request: The request body is malformed or contains invalid data.'
          content:
            application/json:
              schema:
                type: string
        "404":
          description: 'Not Found: The application with the specified ID does not exist.'
          content:
            application/json:
              schema:
                type: string
        "500":
          description: 'Internal Server Error: An unexpected error occurred while processing the request.'
          content:
            application/json:
              schema:
                type: string
      summary: Update an application
      tags:
      - applications

components:
  schemas:
    model.Application:
      type: object
      properties:
        auth_flow_graph_id:
          type: string
          items:
            type: string
        callback_url:
          type: array
          items:
            type: string
        client_id:
          type: string
        client_secret:
          type: string
        description:
          type: string
        id:
          type: string
        org_id:
          type: string
        name:
          type: string
        supported_grant_types:
          type: array
          items:
            type: string
